@host = http://localhost:8080

### 1. Health check — confirm the app is up
GET {{host}}/health

### 2. Ingest sample documents (run ONCE)
POST {{host}}/ingest

### 3. Semantic search ONLY — see what Vector Search returns (no OpenAI - Generation)
POST {{host}}/search
Content-Type: application/json

{
  "question": "Which rainforest animals are most dangerous and why?"
}

### 4. Ask a question - RAG
POST {{host}}/chat
Content-Type: application/json

{
  "question": "Which rainforest animals are most dangerous and why?"
}
