quarkus.mongodb.connection-string=${MONGODB_URI}
quarkus.mongodb.database=library

# ReadPreference: primary | primaryPreferred | secondary | secondaryPreferred | nearest
mongodb.read-preference=primaryPreferred

# Connection Pool
mongodb.pool.max-size=2
mongodb.pool.min-size=1
mongodb.pool.max-wait-time-ms=1000
mongodb.pool.max-connection-idle-time-ms=60000
mongodb.pool.max-connection-life-time-ms=300000