quarkus.mongodb.connection-string=${MONGODB_URI}
quarkus.mongodb.database=library

# ReadPreference: primary | primaryPreferred | secondary | secondaryPreferred | nearest
mongodb.read-preference=primary

# Connection Pool
mongodb.pool.max-size=100
mongodb.pool.min-size=0
mongodb.pool.max-connection-idle-time-ms=0
mongodb.pool.max-connection-life-time-ms=0